// frontend/src/lib/components/public/PublicationCard.svelte
<script lang="ts">
  import { ArrowUpRight, FileText } from 'lucide-svelte';
  import { Card } from '@sivir-ui/svelte';
  import type { Publication } from '$lib/api';
  import TagChip from './TagChip.svelte';
  let { publication }: { publication: Publication } = $props();
</script>
<Card.Root class="site-card !rounded-2xl !p-5 transition-all hover:-translate-y-0.5 sm:!p-7">
  <div class="flex items-start justify-between gap-4">
    <div class="space-y-3">
      <div class="flex flex-wrap items-center gap-2">
        {#if publication.year}<span class="site-eyebrow">{publication.year}</span>{/if}
        {#if publication.featured}<span class="site-chip">Featured</span>{/if}
      </div>
      <h3 class="text-lg font-bold leading-snug tracking-tight sm:text-xl">{publication.title}</h3>
      {#if publication.authors}<p class="site-copy text-sm">{publication.authors}</p>{/if}
      {#if publication.venue}<p class="text-sm font-semibold text-[var(--site-accent)]">{publication.venue}</p>{/if}
      {#if publication.abstract}<p class="site-copy line-clamp-3 text-sm">{publication.abstract}</p>{/if}
      {#if publication.tags.length}<div class="flex flex-wrap gap-2">{#each publication.tags as tag (tag.id)}<TagChip {tag}/>{/each}</div>{/if}
      <div class="flex flex-wrap gap-4 pt-1 text-sm font-semibold text-[var(--site-accent)]">
        {#if publication.url}<a class="inline-flex items-center gap-1" href={publication.url} target="_blank" rel="noreferrer">Read paper <ArrowUpRight size={15}/></a>{/if}
        {#if publication.doi}<a class="inline-flex items-center gap-1" href={`https://doi.org/${publication.doi}`} target="_blank" rel="noreferrer">DOI <ArrowUpRight size={15}/></a>{/if}
        {#if publication.file_url}<a class="inline-flex items-center gap-1" href={publication.file_url} target="_blank" rel="noreferrer"><FileText size={15}/> PDF</a>{/if}
      </div>
    </div>
  </div>
</Card.Root>

// frontend/components/publication-card.tsx
import { ExternalLink, FileText, Star } from "lucide-react";
import { TagChip } from "@/components/public/tag-chip";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import type { Publication } from "@/lib/api";

export function PublicationCard({ pub }: { pub: Publication }) {
  return (
    <Card className="surface-card">
      <CardContent className="space-y-2">
        <h3 className="flex items-start gap-1.5 font-semibold leading-snug">
          {pub.featured && <Star className="mt-1 size-3.5 shrink-0 fill-primary text-primary" />}
          {pub.title}
        </h3>
        <p className="text-sm text-muted-foreground">
          {[pub.authors, pub.venue, pub.year].filter(Boolean).join(" · ")}
        </p>
        {pub.abstract && <p className="text-sm leading-relaxed">{pub.abstract}</p>}
        {pub.tags.length > 0 && (
          <div className="flex flex-wrap gap-1.5 pt-1">
            {pub.tags.map((t) => (
              <TagChip key={t.id} tag={t} />
            ))}
          </div>
        )}
        {(pub.file_url || pub.doi || pub.url) && (
          <div className="flex flex-wrap gap-2 pt-2">
            {pub.file_url && (
              <Button asChild size="sm" variant="outline">
                <a href={pub.file_url} target="_blank" rel="noreferrer">
                  <FileText className="size-4" /> PDF
                </a>
              </Button>
            )}
            {pub.doi && (
              <Button asChild size="sm" variant="ghost">
                <a href={`https://doi.org/${pub.doi}`} target="_blank" rel="noreferrer">
                  <ExternalLink className="size-4" /> DOI
                </a>
              </Button>
            )}
            {pub.url && (
              <Button asChild size="sm" variant="ghost">
                <a href={pub.url} target="_blank" rel="noreferrer">
                  <ExternalLink className="size-4" /> Link
                </a>
              </Button>
            )}
          </div>
        )}
      </CardContent>
    </Card>
  );
}
