// frontend/app/admin/page.tsx
"use client";

import { LogOut } from "lucide-react";
import { useRouter } from "next/navigation";
import { useCallback } from "react";
import { AppearanceEditor } from "@/components/admin/appearance-editor";
import { DataManager } from "@/components/admin/data-manager";
import { FeatureEditor } from "@/components/admin/feature-editor";
import { HeadshotEditor } from "@/components/admin/headshot-editor";
import { ProfileEditor } from "@/components/admin/profile-editor";
import { ProjectManager } from "@/components/admin/project-manager";
import { PublicationManager } from "@/components/admin/publication-manager";
import { SkillManager } from "@/components/admin/skill-manager";
import { TagManager } from "@/components/admin/tag-manager";
import { TalkManager } from "@/components/admin/talk-manager";
import { useAdminData } from "@/components/admin/use-admin-data";
import { ModeToggle } from "@/components/mode-toggle";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { logout } from "@/lib/client";

export default function AdminDashboard() {
  const router = useRouter();
  const onUnauthed = useCallback(() => router.push("/admin/login"), [router]);
  const { config, setConfig, tags, pubs, talks, projects, skills, reload } =
    useAdminData(onUnauthed);

  if (!config) {
    return <div className="mx-auto max-w-3xl px-5 py-16 text-muted-foreground">Loading…</div>;
  }

  return (
    <div className="mx-auto max-w-3xl px-5 py-8">
      <div className="mb-6 flex items-center justify-between gap-2">
        <h1 className="text-xl font-bold">OpenVitae Admin</h1>
        <div className="flex shrink-0 items-center gap-2">
          <ModeToggle />
          <Button asChild variant="outline" size="sm">
            <a href="/" target="_blank" rel="noreferrer">
              View site
            </a>
          </Button>
          <Button
            variant="ghost"
            size="sm"
            onClick={() => {
              logout();
              router.push("/admin/login");
            }}
          >
            <LogOut className="size-4" /> Sign out
          </Button>
        </div>
      </div>

      <Tabs defaultValue="profile">
        <TabsList className="mb-4 w-full max-w-full justify-start overflow-x-auto">
          <TabsTrigger value="profile">Profile</TabsTrigger>
          <TabsTrigger value="appearance">Appearance</TabsTrigger>
          <TabsTrigger value="publications">Publications</TabsTrigger>
          <TabsTrigger value="talks">Talks</TabsTrigger>
          <TabsTrigger value="projects">Projects</TabsTrigger>
          <TabsTrigger value="skills">Skills</TabsTrigger>
          <TabsTrigger value="tags">Tags</TabsTrigger>
          <TabsTrigger value="data">Data</TabsTrigger>
        </TabsList>

        <TabsContent value="profile" className="space-y-6">
          <ProfileEditor config={config} setConfig={setConfig} />
          <HeadshotEditor config={config} setConfig={setConfig} />
          <FeatureEditor config={config} setConfig={setConfig} />
        </TabsContent>

        <TabsContent value="appearance">
          <AppearanceEditor config={config} setConfig={setConfig} />
        </TabsContent>

        <TabsContent value="publications">
          <PublicationManager pubs={pubs} tags={tags} reload={reload} />
        </TabsContent>

        <TabsContent value="talks">
          <TalkManager talks={talks} reload={reload} />
        </TabsContent>

        <TabsContent value="projects">
          <ProjectManager projects={projects} tags={tags} skills={skills} reload={reload} />
        </TabsContent>

        <TabsContent value="skills">
          <SkillManager skills={skills} reload={reload} />
        </TabsContent>

        <TabsContent value="tags">
          <TagManager tags={tags} reload={reload} />
        </TabsContent>

        <TabsContent value="data">
          <DataManager reload={reload} />
        </TabsContent>
      </Tabs>
    </div>
  );
}

// frontend/src/routes/admin/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { goto } from '$app/navigation';
  import { Button } from '@sivir-ui/svelte';
  import { LogOut } from 'lucide-svelte';
  import type { Project, Publication, SiteConfig, Skill, Tag, Talk } from '$lib/api';
  import { api, isAuthed, logout } from '$lib/client';
  import ProfileEditor from '$lib/components/admin/ProfileEditor.svelte';
  import HeadshotEditor from '$lib/components/admin/HeadshotEditor.svelte';
  import FeatureEditor from '$lib/components/admin/FeatureEditor.svelte';
  import AppearanceEditor from '$lib/components/admin/AppearanceEditor.svelte';
  import EntityEditor from '$lib/components/admin/EntityEditor.svelte';
  import ImportEditor from '$lib/components/admin/ImportEditor.svelte';
  import DataEditor from '$lib/components/admin/DataEditor.svelte';

  let config = $state<SiteConfig | null>(null);
  let tags = $state<Tag[]>([]); let publications = $state<Publication[]>([]);
  let talks = $state<Talk[]>([]); let projects = $state<Project[]>([]); let skills = $state<Skill[]>([]);
  let active = $state('profile'); let message = $state(''); let error = $state(false);
  const tabs = ['profile', 'appearance', 'publications', 'talks', 'projects', 'skills', 'tags', 'data'];
  function report(value: string, isError = false) { message = value; error = isError; window.setTimeout(() => { if (message === value) message = ''; }, 5000); }
  async function reload() {
    [config, tags, publications, talks, projects, skills] = await Promise.all([
      api.getConfig(), api.listTags(), api.listPublications(), api.listTalks(), api.listProjects(), api.listSkills()
    ]);
  }
  onMount(() => {
    api.getAuthMode().then(({ mode }) => {
      if (mode !== 'proxy' && !isAuthed()) return goto('/admin/login');
      return reload();
    }).catch((cause) => report(String(cause), true));
  });
  function signOut() { logout(); goto('/admin/login'); }
</script>
<svelte:head><title>Admin · OpenVitae</title></svelte:head>
<main class="site-shell py-10 md:py-14">
  <div class="mb-9 flex flex-wrap items-end justify-between gap-4"><div><p class="site-eyebrow mb-2">Your workspace</p><h1 class="site-heading">Make it yours<span class="text-[var(--site-accent)]">.</span></h1></div><div class="flex gap-2"><Button href="/" variant="secondary" size="sm">View site ↗</Button><Button variant="quiet" size="sm" onclick={signOut}><LogOut size={15}/> Sign out</Button></div></div>
  {#if message}<div role="status" class="mb-5 rounded-xl border p-3 text-sm" class:border-red-400={error} class:text-red-500={error}>{message}</div>{/if}
  {#if config}
    <div class="grid gap-8 lg:grid-cols-[200px_minmax(0,1fr)]">
      <nav aria-label="Admin sections" class="flex gap-1 overflow-x-auto lg:flex-col">{#each tabs as tab}<button class:chosen={active === tab} type="button" class="shrink-0 rounded-xl px-4 py-3 text-left text-sm font-semibold capitalize" onclick={() => active = tab}>{tab}</button>{/each}</nav>
      <div class="min-w-0 space-y-5">
        {#if active === 'profile'}<ProfileEditor {config} updated={(value) => config = value} {report}/><HeadshotEditor {config} updated={(value) => config = value} {report}/><FeatureEditor {config} updated={(value) => config = value} {report}/>{/if}
        {#if active === 'appearance'}<AppearanceEditor {config} updated={(value) => config = value} {report}/>{/if}
        {#if active === 'publications'}<ImportEditor {reload} {report}/><EntityEditor kind="publications" items={publications} {tags} {reload} {report}/>{/if}
        {#if active === 'talks'}<EntityEditor kind="talks" items={talks} {reload} {report}/>{/if}
        {#if active === 'projects'}<EntityEditor kind="projects" items={projects} {tags} {skills} {reload} {report}/>{/if}
        {#if active === 'skills'}<EntityEditor kind="skills" items={skills} {reload} {report}/>{/if}
        {#if active === 'tags'}<EntityEditor kind="tags" items={tags} {reload} {report}/>{/if}
        {#if active === 'data'}<DataEditor {reload} {report}/>{/if}
      </div>
    </div>
  {:else}<p class="site-copy py-20">Loading workspace…</p>{/if}
</main>
<style>nav button { color: var(--site-muted); } nav button:hover { background: var(--site-accent-soft); color: var(--site-ink); } nav button.chosen { background: var(--site-accent); color: white; }</style>
