// frontend/src/routes/publications/+page.svelte
<script lang="ts">
  import { ArrowLeft } from 'lucide-svelte';
  import PublicationCard from '$lib/components/public/PublicationCard.svelte';
  import type { PageData } from './$types';
  let { data }: { data: PageData } = $props();
</script>
<svelte:head><title>Publications · {data.config?.profile?.siteName || data.config?.profile?.name || 'OpenVitae'}</title></svelte:head>
<main class="site-shell py-14 md:py-20">
  <a href="/" class="site-copy mb-8 inline-flex items-center gap-2 text-sm hover:text-[var(--site-accent)]"><ArrowLeft size={16}/> Back to home</a>
  <p class="site-eyebrow mb-3">Research archive</p>
  <h1 class="site-heading mb-3">Publications</h1>
  <p class="site-copy mb-9">Browse all work, from recent to earliest.</p>
  <form class="mb-8 flex flex-wrap gap-3" method="GET">
    <label><span class="sr-only">Filter by tag</span><select class="site-field" name="tag" onchange={(event) => event.currentTarget.form?.requestSubmit()}><option value="">All topics</option>{#each data.tags as tag}<option value={tag.slug} selected={data.tag === tag.slug}>{tag.name}</option>{/each}</select></label>
    <label><span class="sr-only">Sort</span><select class="site-field" name="sort" onchange={(event) => event.currentTarget.form?.requestSubmit()}><option value="date_desc" selected={data.sort === 'date_desc'}>Newest first</option><option value="date_asc" selected={data.sort === 'date_asc'}>Oldest first</option></select></label>
  </form>
  <div class="grid gap-4">{#each data.publications as publication (publication.id)}<PublicationCard {publication}/>{:else}<p class="site-copy">No publications found.</p>{/each}</div>
</main>

// frontend/app/publications/page.tsx
import { ArrowLeft } from "lucide-react";
import Link from "next/link";
import { PublicationFilters } from "@/components/public/publication-filters";
import { SectionHeading } from "@/components/public/section-heading";
import { SiteHeader } from "@/components/public/site-header";
import { PublicationCard } from "@/components/publication-card";
import { getPublications, getSiteConfig, getTags, type Publication, type Tag } from "@/lib/api";

export const dynamic = "force-dynamic";

export default async function PublicationsPage({
  searchParams,
}: {
  searchParams: Promise<{ tag?: string; sort?: string }>;
}) {
  const sp = await searchParams;
  const tag = typeof sp.tag === "string" ? sp.tag : undefined;
  const sort = sp.sort === "date_asc" ? "date_asc" : "date_desc";

  let name: string | undefined;
  let tags: Tag[] = [];
  let pubs: Publication[] = [];
  try {
    const [config, allTags, list] = await Promise.all([
      getSiteConfig(),
      getTags(),
      getPublications({ tag, sort }),
    ]);
    name = config.profile?.name;
    tags = allTags;
    pubs = list;
  } catch {
    /* backend down — render empties */
  }

  return (
    <div className="min-h-screen">
      <SiteHeader name={name} />
      <main className="mx-auto max-w-2xl px-5 pb-24 pt-10">
        <Link
          href="/"
          className="mb-4 inline-flex items-center gap-1 text-sm text-muted-foreground hover:text-foreground"
        >
          <ArrowLeft className="size-4" /> Back
        </Link>
        <SectionHeading>All publications</SectionHeading>
        <PublicationFilters tags={tags} activeTag={tag} activeSort={sort} />
        {pubs.length === 0 ? (
          <p className="text-sm text-muted-foreground">No publications found.</p>
        ) : (
          <div className="space-y-3">
            {pubs.map((p) => (
              <PublicationCard key={p.id} pub={p} />
            ))}
          </div>
        )}
      </main>
    </div>
  );
}
