// frontend/src/lib/components/admin/AppearanceEditor.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { Button, Card } from '@sivir-ui/svelte';
  import type { SiteConfig } from '$lib/api';
  import { api } from '$lib/client';
  import { DEFAULT_PALETTE, PALETTES, type ThemeConfig } from '$lib/palettes';
  let { config, updated, report }: { config: SiteConfig; updated: (config: SiteConfig) => void; report: (message: string, error?: boolean) => void } = $props();
  let theme = $state<ThemeConfig>(untrack(() => ({ palette: DEFAULT_PALETTE, ...config.theme })));
  let busy = $state(false);
  function palette(id: string) { theme.palette = id; document.documentElement.dataset.palette = id; }
  function custom(value: string) { theme.customPrimary = value; document.documentElement.style.setProperty('--site-accent', value); }
  async function save() { busy = true; try { updated(await api.updateConfig({ theme: theme as Record<string, string> })); report('Appearance saved'); } catch (error) { report(String(error), true); } finally { busy = false; } }
</script>
<Card.Root class="site-card !rounded-2xl !p-6"><p class="site-eyebrow mb-2">Visual identity</p><h2 class="mb-6 text-2xl font-bold tracking-tight">Appearance</h2>
  <span class="site-label">Palette</span><div class="mb-7 grid grid-cols-2 gap-2 sm:grid-cols-4">{#each PALETTES as option}<button class="flex items-center gap-2 rounded-xl border border-[var(--site-line)] p-3 text-sm font-semibold" class:chosen={theme.palette === option.id} onclick={() => palette(option.id)}><span class="size-5 rounded-full" style:background={option.swatch}></span>{option.name}</button>{/each}</div>
  <div class="grid gap-6 sm:grid-cols-2"><label><span class="site-label">Layout</span><select class="site-field" bind:value={theme.layout}><option value="linear">Scrolling page</option><option value="pages">Section tabs</option></select></label><label><span class="site-label">Default mode</span><select class="site-field" bind:value={theme.defaultMode}><option value="system">System</option><option value="light">Light</option><option value="dark">Dark</option></select></label><label><span class="site-label">Custom accent</span><input type="color" class="site-field h-11" value={theme.customPrimary || '#171717'} oninput={(event) => custom(event.currentTarget.value)}/></label></div>
  <Button class="mt-7" onclick={save} loading={busy}>Save appearance</Button>
</Card.Root>
<style>.chosen { border-color: var(--site-accent); background: var(--site-accent-soft); }</style>

// frontend/components/admin/appearance-editor.tsx
"use client";

import { useState } from "react";
import { toast } from "sonner";
import type { EditorProps } from "@/components/admin/types";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { api } from "@/lib/client";
import { DEFAULT_LAYOUT, DEFAULT_PALETTE, PALETTES, type ThemeConfig } from "@/lib/palettes";

export function AppearanceEditor({ config, setConfig }: EditorProps) {
  const [theme, setTheme] = useState<ThemeConfig>((config.theme as ThemeConfig) || {});
  const [saving, setSaving] = useState(false);
  const selected = theme.palette || DEFAULT_PALETTE;

  function previewPalette(id: string) {
    document.documentElement.setAttribute("data-palette", id);
    setTheme((t) => ({ ...t, palette: id }));
  }
  function previewCustom(hex: string | undefined) {
    const root = document.documentElement;
    if (hex) {
      root.style.setProperty("--primary", hex);
      root.style.setProperty("--ring", hex);
      root.style.setProperty("--primary-foreground", "#ffffff");
    } else {
      root.style.removeProperty("--primary");
      root.style.removeProperty("--ring");
      root.style.removeProperty("--primary-foreground");
    }
    setTheme((t) => ({ ...t, customPrimary: hex }));
  }

  async function save() {
    setSaving(true);
    try {
      const updated = await api.updateConfig({ theme });
      setConfig(updated);
      toast.success("Appearance saved — reload the public site to see it");
    } catch (e) {
      toast.error(String(e));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Appearance</CardTitle>
        <CardDescription>
          Pick a palette — each works in light and dark mode. Visitors can switch mode with the
          toggle.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div>
          <Label className="mb-2 block">Palette</Label>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-4">
            {PALETTES.map((pal) => (
              <button
                key={pal.id}
                type="button"
                onClick={() => previewPalette(pal.id)}
                className={`flex items-center gap-2 rounded-lg border p-2.5 text-sm transition-colors hover:bg-accent ${
                  selected === pal.id ? "border-primary ring-2 ring-ring" : "border-border"
                }`}
              >
                <span
                  className="size-5 shrink-0 rounded-full border"
                  style={{ background: pal.swatch }}
                />
                {pal.name}
              </button>
            ))}
          </div>
        </div>

        <div>
          <Label className="mb-2 block">Layout</Label>
          <div className="flex gap-2">
            {(["linear", "pages"] as const).map((l) => (
              <Button
                key={l}
                type="button"
                size="sm"
                variant={(theme.layout || DEFAULT_LAYOUT) === l ? "default" : "outline"}
                onClick={() => setTheme((t) => ({ ...t, layout: l }))}
                className="capitalize"
              >
                {l}
              </Button>
            ))}
          </div>
          <p className="mt-1 text-sm text-muted-foreground">
            Linear stacks every section on one scrolling page; Pages shows them as tabs.
          </p>
        </div>

        <div>
          <Label className="mb-2 block">Default mode for new visitors</Label>
          <div className="flex gap-2">
            {(["light", "dark", "system"] as const).map((m) => (
              <Button
                key={m}
                type="button"
                size="sm"
                variant={(theme.defaultMode || "system") === m ? "default" : "outline"}
                onClick={() => setTheme((t) => ({ ...t, defaultMode: m }))}
                className="capitalize"
              >
                {m}
              </Button>
            ))}
          </div>
        </div>

        <div>
          <Label className="mb-2 block">Advanced: custom accent color</Label>
          <div className="flex items-center gap-2">
            <Input
              type="color"
              className="h-10 w-14 p-1"
              value={theme.customPrimary || "#000000"}
              onChange={(e) => previewCustom(e.target.value)}
            />
            <Input
              className="max-w-40"
              placeholder="#3b82f6"
              value={theme.customPrimary || ""}
              onChange={(e) => previewCustom(e.target.value || undefined)}
            />
            {theme.customPrimary && (
              <Button variant="ghost" size="sm" onClick={() => previewCustom(undefined)}>
                Clear
              </Button>
            )}
          </div>
          <p className="mt-1 text-sm text-muted-foreground">
            Overrides the palette&apos;s primary color when set.
          </p>
        </div>

        <Button onClick={save} disabled={saving}>
          Save appearance
        </Button>
      </CardContent>
    </Card>
  );
}
