// frontend/components/admin/feature-editor.tsx
"use client";

import { useState } from "react";
import { toast } from "sonner";
import type { EditorProps } from "@/components/admin/types";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Label } from "@/components/ui/label";
import { Switch } from "@/components/ui/switch";
import { api } from "@/lib/client";

const FEATURE_KEYS: { key: string; label: string; hint: string }[] = [
  { key: "about", label: "About section", hint: "Show your bio." },
  { key: "publications", label: "Publications", hint: "Show the publications list." },
  { key: "talks", label: "Talks", hint: "Show the talks section." },
  { key: "projects", label: "Projects", hint: "Show the personal projects section." },
  { key: "skills", label: "Skills", hint: "Show the skills section." },
  { key: "contact", label: "Contact", hint: "Show email and links." },
  { key: "headshot", label: "Headshot", hint: "Show your photo." },
];

export function FeatureEditor({ config, setConfig }: EditorProps) {
  const [features, setFeatures] = useState<Record<string, boolean>>(config.features || {});
  const [saving, setSaving] = useState(false);

  async function toggle(key: string, value: boolean) {
    const next = { ...features, [key]: value };
    setFeatures(next);
    setSaving(true);
    try {
      const updated = await api.updateConfig({ features: next });
      setConfig(updated);
      toast.success("Features updated");
    } catch (e) {
      toast.error(String(e));
    } finally {
      setSaving(false);
    }
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Features</CardTitle>
        <CardDescription>Toggle sections of your public site on or off.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {FEATURE_KEYS.map(({ key, label, hint }) => (
          <div key={key} className="flex items-center justify-between">
            <div>
              <Label htmlFor={`feat-${key}`}>{label}</Label>
              <p className="text-sm text-muted-foreground">{hint}</p>
            </div>
            <Switch
              id={`feat-${key}`}
              checked={features[key] !== false}
              disabled={saving}
              onCheckedChange={(v) => toggle(key, v)}
            />
          </div>
        ))}
      </CardContent>
    </Card>
  );
}

// frontend/src/lib/components/admin/FeatureEditor.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { Card } from '@sivir-ui/svelte';
  import type { SiteConfig } from '$lib/api';
  import { api } from '$lib/client';
  let { config, updated, report }: { config: SiteConfig; updated: (config: SiteConfig) => void; report: (message: string, error?: boolean) => void } = $props();
  let features = $state(untrack(() => ({ ...config.features })));
  const labels: Record<string, string> = { about: 'About & skills', publications: 'Publications', talks: 'Talks', projects: 'Projects', skills: 'Skills', contact: 'Contact', headshot: 'Headshot' };
  async function toggle(key: string, checked: boolean) { const previous = features[key]; features[key] = checked; try { updated(await api.updateConfig({ features })); report('Sections updated'); } catch (error) { features[key] = previous; report(String(error), true); } }
</script>
<Card.Root class="site-card !rounded-2xl !p-6"><p class="site-eyebrow mb-2">What visitors see</p><h2 class="mb-5 text-2xl font-bold tracking-tight">Sections</h2><div class="divide-y divide-[var(--site-line)]">{#each Object.entries(labels) as [key, label]}<label class="flex cursor-pointer items-center justify-between py-3 text-sm font-semibold">{label}<input type="checkbox" checked={features[key] !== false} onchange={(event) => toggle(key, event.currentTarget.checked)} class="size-5 accent-[var(--site-accent)]"/></label>{/each}</div></Card.Root>
