// frontend/components/admin/profile-editor.tsx
"use client";

import { Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { Field } from "@/components/admin/field";
import { GithubImport } from "@/components/admin/github-import";
import type { EditorProps } from "@/components/admin/types";
import { SocialIcon } from "@/components/social-icon";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { api, type GithubImportResult } from "@/lib/client";
import { SOCIAL_PLATFORMS } from "@/lib/socials";

export function ProfileEditor({ config, setConfig }: EditorProps) {
  const [p, setP] = useState(config.profile || {});
  const links = p.links || [];
  const socials = p.socials || [];
  const [saving, setSaving] = useState(false);

  async function save() {
    setSaving(true);
    try {
      const updated = await api.updateConfig({ profile: p });
      setConfig(updated);
      toast.success("Profile saved");
    } catch (e) {
      toast.error(String(e));
    } finally {
      setSaving(false);
    }
  }

  function mergeGithub(r: GithubImportResult) {
    setP((prev) => {
      const links = [...(prev.links || [])];
      for (const l of r.links) {
        if (!links.some((x) => x.url === l.url)) links.push(l);
      }
      const socials = [...(prev.socials || [])];
      for (const s of r.socials) {
        if (!socials.some((x) => x.platform === s.platform)) socials.push(s);
      }
      return {
        ...prev,
        name: r.name || prev.name || "",
        bio: r.bio || prev.bio || "",
        location: r.location || prev.location || "",
        links,
        socials,
      };
    });
  }

  return (
    <Card>
      <CardHeader>
        <CardTitle>Profile</CardTitle>
        <CardDescription>Your name, title, and contact details.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <GithubImport
          onProfile={mergeGithub}
          onHeadshot={(url) => setConfig({ ...config, headshot_url: url })}
        />
        <div className="grid gap-4 sm:grid-cols-2">
          <Field label="Name">
            <Input value={p.name || ""} onChange={(e) => setP({ ...p, name: e.target.value })} />
          </Field>
          <Field label="Title">
            <Input value={p.title || ""} onChange={(e) => setP({ ...p, title: e.target.value })} />
          </Field>
          <Field label="Location">
            <Input
              value={p.location || ""}
              onChange={(e) => setP({ ...p, location: e.target.value })}
            />
          </Field>
          <Field label="Email">
            <Input value={p.email || ""} onChange={(e) => setP({ ...p, email: e.target.value })} />
          </Field>
        </div>
        <Field label="Bio">
          <Textarea
            rows={4}
            value={p.bio || ""}
            onChange={(e) => setP({ ...p, bio: e.target.value })}
          />
          <p className="text-sm text-muted-foreground">Markdown supported.</p>
        </Field>

        <div className="space-y-2">
          <Label>Links</Label>
          {links.map((l, i) => (
            <div key={i} className="flex gap-2">
              <Input
                placeholder="Label"
                value={l.label}
                onChange={(e) => {
                  const next = [...links];
                  next[i] = { ...next[i], label: e.target.value };
                  setP({ ...p, links: next });
                }}
              />
              <Input
                placeholder="https://…"
                value={l.url}
                onChange={(e) => {
                  const next = [...links];
                  next[i] = { ...next[i], url: e.target.value };
                  setP({ ...p, links: next });
                }}
              />
              <Button
                variant="outline"
                size="icon"
                onClick={() => setP({ ...p, links: links.filter((_, j) => j !== i) })}
              >
                <Trash2 className="size-4" />
              </Button>
            </div>
          ))}
          <Button
            variant="secondary"
            size="sm"
            onClick={() => setP({ ...p, links: [...links, { label: "", url: "" }] })}
          >
            <Plus className="size-4" /> Add link
          </Button>
        </div>

        <div className="space-y-2">
          <Label>Social links</Label>
          {socials.map((s, i) => (
            <div key={i} className="flex gap-2">
              <Select
                value={s.platform}
                onValueChange={(platform) => {
                  const next = [...socials];
                  next[i] = { ...next[i], platform };
                  setP({ ...p, socials: next });
                }}
              >
                <SelectTrigger className="w-44 shrink-0">
                  <SelectValue placeholder="Platform" />
                </SelectTrigger>
                <SelectContent>
                  {SOCIAL_PLATFORMS.map((plat) => (
                    <SelectItem key={plat.id} value={plat.id}>
                      <SocialIcon platform={plat.id} className="size-4" />
                      {plat.name}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              <Input
                placeholder={
                  SOCIAL_PLATFORMS.find((plat) => plat.id === s.platform)?.placeholder ||
                  "https://…"
                }
                value={s.url}
                onChange={(e) => {
                  const next = [...socials];
                  next[i] = { ...next[i], url: e.target.value };
                  setP({ ...p, socials: next });
                }}
              />
              <Button
                variant="outline"
                size="icon"
                onClick={() => setP({ ...p, socials: socials.filter((_, j) => j !== i) })}
              >
                <Trash2 className="size-4" />
              </Button>
            </div>
          ))}
          <Button
            variant="secondary"
            size="sm"
            onClick={() => setP({ ...p, socials: [...socials, { platform: "github", url: "" }] })}
          >
            <Plus className="size-4" /> Add social link
          </Button>
        </div>

        <Button onClick={save} disabled={saving}>
          Save profile
        </Button>
      </CardContent>
    </Card>
  );
}

// frontend/src/lib/components/admin/ProfileEditor.svelte
<script lang="ts">
  import { untrack } from 'svelte';
  import { Button, Card } from '@sivir-ui/svelte';
  import { Plus, Trash2 } from 'lucide-svelte';
  import type { SiteConfig } from '$lib/api';
  import { api } from '$lib/client';
  import Field from './Field.svelte';
  let { config, updated, report }: { config: SiteConfig; updated: (config: SiteConfig) => void; report: (message: string, error?: boolean) => void } = $props();
  let profile = $state(untrack(() => ({ ...config.profile, links: [...(config.profile.links || [])], socials: [...(config.profile.socials || [])] })));
  let busy = $state(false);
  async function save() {
    busy = true;
    try { updated(await api.updateConfig({ profile })); report('Profile saved'); }
    catch (error) { report(String(error), true); }
    finally { busy = false; }
  }
  async function importGithub(username: string) {
    if (!username.trim()) return;
    busy = true;
    try {
      const result = await api.importGithub(username.trim());
      profile = { ...profile, name: result.name || profile.name, bio: result.bio || profile.bio, location: result.location || profile.location, links: [...(profile.links || []), ...result.links.filter((link) => !profile.links?.some((existing) => existing.url === link.url))], socials: [...(profile.socials || []), ...result.socials.filter((social) => !profile.socials?.some((existing) => existing.url === social.url))] };
      report('GitHub profile loaded. Save to keep it.');
    } catch (error) { report(String(error), true); }
    finally { busy = false; }
  }
  async function importGithubPhoto() {
    if (!github.trim()) return;
    busy = true;
    try {
      const result = await api.importGithubHeadshot(github.trim());
      updated({ ...config, headshot_url: result.headshot_url });
      report('GitHub photo imported');
    } catch (error) { report(String(error), true); }
    finally { busy = false; }
  }
  let github = $state('');
</script>
<Card.Root class="site-card !rounded-2xl !p-6"><p class="site-eyebrow mb-2">Make it yours</p><h2 class="mb-6 text-2xl font-bold tracking-tight">Profile</h2>
  <div class="mb-7 flex flex-wrap gap-2"><input class="site-field max-w-xs" placeholder="GitHub username" bind:value={github}/><Button variant="secondary" onclick={() => importGithub(github)} loading={busy}>Import GitHub</Button><Button variant="quiet" onclick={importGithubPhoto} disabled={busy}>Use GitHub photo</Button></div>
  <div class="grid gap-5 sm:grid-cols-2"><Field label="Site title" bind:value={profile.siteName}/><Field label="Name" bind:value={profile.name}/><Field label="Title" bind:value={profile.title}/><Field label="Location" bind:value={profile.location}/><Field label="Email" type="email" bind:value={profile.email}/><div class="sm:col-span-2"><Field label="Bio (Markdown)" multiline bind:value={profile.bio}/></div></div>
  <div class="mt-7"><div class="mb-3 flex items-center justify-between"><h3 class="font-bold">Links</h3><Button variant="quiet" size="sm" onclick={() => profile.links = [...(profile.links || []), { label: '', url: '' }]}><Plus size={14}/> Add</Button></div>{#each profile.links || [] as link, index}<div class="mb-2 flex gap-2"><input class="site-field" placeholder="Label" bind:value={link.label}/><input class="site-field" type="url" placeholder="https://" bind:value={link.url}/><button aria-label="Remove link" onclick={() => profile.links = profile.links?.filter((_, i) => i !== index)}><Trash2 size={16}/></button></div>{/each}</div>
  <div class="mt-7"><div class="mb-3 flex items-center justify-between"><h3 class="font-bold">Social links</h3><Button variant="quiet" size="sm" onclick={() => profile.socials = [...(profile.socials || []), { platform: 'github', url: '' }]}><Plus size={14}/> Add</Button></div>{#each profile.socials || [] as social, index}<div class="mb-2 flex gap-2"><input class="site-field max-w-36" placeholder="Platform" bind:value={social.platform}/><input class="site-field" type="url" placeholder="https://" bind:value={social.url}/><button aria-label="Remove social link" onclick={() => profile.socials = profile.socials?.filter((_, i) => i !== index)}><Trash2 size={16}/></button></div>{/each}</div>
  <Button class="mt-7" onclick={save} loading={busy}>Save profile</Button>
</Card.Root>
